//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedalList
    {
        public int ID { get; set; }
        public int MedalType { get; set; }
        public int SportID { get; set; }
        public int AthleteID { get; set; }
        public System.DateTime ConfirmTime { get; set; }
    
        public virtual Athlete Athlete { get; set; }
        public virtual Sport Sport { get; set; }
    }
}
